### ISSUE TITLE
未能识别

### ISSUE THREAD

**Issue by willzoe** [duanshengliu/End-to-end-for-chinese-plate-recognition#2]
从自己拍摄的视频中截取了几张图片作为测试，有一些角度的车牌未能被识别，如下所示：

![image](https://user-images.githubusercontent.com/14708901/87275242-479f6b00-c510-11ea-8ded-f895e3b67edf.png)

这种情况是因为unet没有正确分割出车牌吗？

**Comment by duanshengliu** [comment]
是的，应该是我训练u-net里面类似这种倾斜角度的还是不够多，所以没有识别




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duanshengliu/End-to-end-for-chinese-plate-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 中午1:54
收件人:&nbsp;"duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[duanshengliu/End-to-end-for-chinese-plate-recognition] 未能识别 (#2)





 
从自己拍摄的视频中截取了几张图片作为测试，有一些角度的车牌未能被识别，如下所示：
 

 
这种情况是因为unet没有正确分割出车牌吗？

**Comment by willzoe** [comment]
你有用过[CCPD数据集](https://github.com/detectRecog/CCPD)吗？是否可以使用CCPD数据集进行训练？

**Comment by duanshengliu** [comment]
可以用，我大部分用的都是CCPD数据集，小部分是自己上网爬，最后统整理到一起的，我u-net只训练了1200多张，cnn训练的多，有3w多张




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duanshengliu/End-to-end-for-chinese-plate-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 下午3:00
收件人:&nbsp;"duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"不啻逍遥然"<1069033158@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [duanshengliu/End-to-end-for-chinese-plate-recognition] 未能识别 (#2)





 
你有用过CCPD数据集吗？是否可以使用CCPD数据集进行训练？

**Comment by willzoe** [comment]
使用CCPD训练u-net和cnn需要进行标注吗？

另外，您是否用CCPD训练过mobilenet-ssd？

**Comment by duanshengliu** [comment]
1.关于u-net，我是从ccpd里面抽取了一小部分加上我收集的一些图片，然后用labelme自己标注的
2.关于cnn识别部分，我是利用ccpd的图片文件名中含有完整的车牌的信息，写个代码提取出来后，再使用u-net分割和矫正得到宽240*80的cnn训练集的
3.没有用CCPD训练过mobilenet-ssd


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duanshengliu/End-to-end-for-chinese-plate-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 下午3:17
收件人:&nbsp;"duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"不啻逍遥然"<1069033158@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [duanshengliu/End-to-end-for-chinese-plate-recognition] 未能识别 (#2)





 
使用CCPD训练u-net和cnn需要进行标注吗？
 
另外，您是否用CCPD训练过mobilenet-ssd？
 
—
You are receiving this because you commented.
Reply to this&nbsp;发送email directly, view it on GitHub, or unsubscribe.

**Comment by willzoe** [comment]
可以使用您训练u-net和cnn的数据集吗？

我的邮箱是willzoe@foxmail.com

**Comment by LIShuo-debug** [comment]
请问可以给一份您训练u-net和cnn的数据集吗？
我的邮箱是：596348603@qq.com，非常感谢！
